# Intermediate in Pandas

## Content:
- Task review: 20 mins
- Descriptive statistics using Pandas: 20 mins
- Amplifying data: 30 mins
    - Merge
    - Join
    - Concatenate
    - Append
- Using functions: 20 mins
- Lambda functions: 20 mins
- Test: 10 mins

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Some basics stats using Pandas

In [13]:
# We called datasets included in Seaborn library
# 'load_dataset' parse data as a Dataframe
# df = sns.load_dataset('planets')
df = pd.read_csv('https://raw.githubusercontent.com/crishernandezmaps/python_training/master/data/tobacco.csv',sep=',')
df.tail(10)

Indicator PUBLISH STATES  Year  \
6198  Average -  cigarette currency      Published  2014   
6199  Average -  cigarette currency      Published  2014   
6200  Average -  cigarette currency      Published  2012   
6201  Average -  cigarette currency      Published  2012   
6202  Average -  cigarette currency      Published  2012   
6203  Average -  cigarette currency      Published  2014   
6204  Average -  cigarette currency      Published  2012   
6205  Average -  cigarette currency      Published  2014   
6206  Average -  cigarette currency      Published  2014   
6207  Average -  cigarette currency      Published  2012   

                 WHO region       Country Display Value  Numeric  Low  High  \
6198        Western Pacific      Malaysia           MYR      NaN  NaN   NaN   
6199               Americas          Peru           PEN      NaN  NaN   NaN   
6200        Western Pacific   Philippines           PHP      NaN  NaN   NaN   
6201                 Europe        Sweden           SEK      NaN  NaN   NaN   
6202        Western Pacific     Singapore           SGD      NaN  NaN   NaN   
6203                 Africa  Sierra Leone           SLL      NaN  NaN   NaN   
6204               Americas       Ecuador           USD      NaN  NaN   NaN   
6205                 Africa      Zimbabwe           USD      NaN  NaN   NaN   
6206                 Africa       Senegal           XOF      NaN  NaN   NaN   
6207  Eastern Mediterranean         Yemen           YER      NaN  NaN   NaN   

     Comments  
6198      NaN  
6199      NaN  
6200      NaN  
6201      NaN  
6202      NaN  
6203      NaN  
6204      NaN  
6205      NaN  
6206      NaN  
6207      NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6208 entries, 0 to 6207
Data columns (total 10 columns):
Indicator         6208 non-null object
PUBLISH STATES    6208 non-null object
Year              6208 non-null int64
WHO region        6208 non-null object
Country           6208 non-null object
Display Value     6208 non-null object
Numeric           2796 non-null float64
Low               0 non-null float64
High              0 non-null float64
Comments          2431 non-null object
dtypes: float64(3), int64(1), object(6)
memory usage: 485.1+ KB


In [20]:
df['Year'].sum()
df['Year'].cumsum().tail()
df['Year'].mean()

2011.0

In [24]:
df['Country'].describe()

count                                 6208
unique                                 194
top       Democratic Republic of the Congo
freq                                    32
Name: Country, dtype: object

In [5]:
df['Year'].count()
# df['Year'].mean()
# df['Year'].std()
# df['Year'].min()
# df['Year'].max()
# df['Year'].median()

513

In [30]:
x = df['Year'].std()
print('La desviacion estandar del año es: ' + str(round(x,3)))

La desviacion estandar del año es: 2.236


In [35]:
print(df['Year'].mean(),df['Year'].describe()[2])

2011.0 2.236248094941582


In [36]:
# df.corr()
df.cov()

Year       Numeric  Low  High
Year       5.000806  1.034956e+02  NaN   NaN
Numeric  103.495630  2.853145e+06  NaN   NaN
Low             NaN           NaN  NaN   NaN
High            NaN           NaN  NaN   NaN

In [8]:
df.sort_index(axis=0, level=None, ascending=True, inplace=True)

In [9]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [10]:
df.dropna(axis=0, how='any', inplace=True)
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

## Join, Merge, Append and Concatenate dataframes 

In [11]:
a = pd.DataFrame(np.random.random((5,3)), columns=['x1','x2','x3'])
b = pd.DataFrame(np.random.random((6,5)), columns=['y1','y2','x3','y4','y5'])

In [12]:
a

x1        x2        x3
0  0.165384  0.212198  0.597271
1  0.826571  0.305936  0.992390
2  0.584198  0.127870  0.744233
3  0.382577  0.383839  0.062651
4  0.457695  0.348093  0.861283

In [13]:
b

y1        y2        x3        y4        y5
0  0.934557  0.902908  0.502654  0.500391  0.196027
1  0.899578  0.289798  0.441114  0.616425  0.540659
2  0.459057  0.236640  0.777243  0.136283  0.428242
3  0.633913  0.400254  0.539142  0.971130  0.530622
4  0.362965  0.662236  0.743129  0.096773  0.372263
5  0.353321  0.747637  0.885137  0.990181  0.209602

In [14]:
a.insert(0, 'ID', range(879, 879 + len(a)))

In [15]:
b.insert(0, 'ID', range(880, 880 + len(b)))

In [16]:
a

ID        x1        x2        x3
0  879  0.165384  0.212198  0.597271
1  880  0.826571  0.305936  0.992390
2  881  0.584198  0.127870  0.744233
3  882  0.382577  0.383839  0.062651
4  883  0.457695  0.348093  0.861283

In [17]:
b

ID        y1        y2        x3        y4        y5
0  880  0.934557  0.902908  0.502654  0.500391  0.196027
1  881  0.899578  0.289798  0.441114  0.616425  0.540659
2  882  0.459057  0.236640  0.777243  0.136283  0.428242
3  883  0.633913  0.400254  0.539142  0.971130  0.530622
4  884  0.362965  0.662236  0.743129  0.096773  0.372263
5  885  0.353321  0.747637  0.885137  0.990181  0.209602

#### Join/Merge 

In [18]:
pd.merge(a, b, on='ID')
pd.merge(a, b, on=['ID','x3'])
pd.merge(a, b, how='outer', on='ID')
pd.merge(a, b, how='inner', on=['ID','x3'])
pd.merge(a, b, how='outer', on=['ID','x3'])
pd.merge(a, b, on=['ID'], how='inner')

ID        x1        x2      x3_x        y1        y2      x3_y        y4  \
0  880  0.826571  0.305936  0.992390  0.934557  0.902908  0.502654  0.500391   
1  881  0.584198  0.127870  0.744233  0.899578  0.289798  0.441114  0.616425   
2  882  0.382577  0.383839  0.062651  0.459057  0.236640  0.777243  0.136283   
3  883  0.457695  0.348093  0.861283  0.633913  0.400254  0.539142  0.971130   

         y5  
0  0.196027  
1  0.540659  
2  0.428242  
3  0.530622

##### Append/Concat 

In [19]:
# List of dataframes
frames = [a,b]

# a.append(b)
pd.concat(frames)
# # pd.concat(frames, keys=['a', 'b'])
# # pd.concat(frames, axis=1)
# # # pd.concat(frames, axis=1, join='outer') # default
# # pd.concat(frames, axis=1, join='inner')

ID        x1        x2        x3        y1        y2        y4        y5
0  879  0.165384  0.212198  0.597271       NaN       NaN       NaN       NaN
1  880  0.826571  0.305936  0.992390       NaN       NaN       NaN       NaN
2  881  0.584198  0.127870  0.744233       NaN       NaN       NaN       NaN
3  882  0.382577  0.383839  0.062651       NaN       NaN       NaN       NaN
4  883  0.457695  0.348093  0.861283       NaN       NaN       NaN       NaN
0  880       NaN       NaN  0.502654  0.934557  0.902908  0.500391  0.196027
1  881       NaN       NaN  0.441114  0.899578  0.289798  0.616425  0.540659
2  882       NaN       NaN  0.777243  0.459057  0.236640  0.136283  0.428242
3  883       NaN       NaN  0.539142  0.633913  0.400254  0.971130  0.530622
4  884       NaN       NaN  0.743129  0.362965  0.662236  0.096773  0.372263
5  885       NaN       NaN  0.885137  0.353321  0.747637  0.990181  0.209602

## Using Functions 

In [20]:
# How to transform all the numbers on a list to strings

listOfNumbers = np.arange(10)
listOfNumbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Let's try a for loop
transformedElements = []
for i in listOfNumbers:
    transformedElements.append(i.astype(str))

transformedElements

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [22]:
# Transform all this elements of this lists to strings

lists = np.random.randint(5, size=(5, 10)) # Numpy array with five lists of 10 elements
lists

array([[0, 3, 2, 3, 3, 3, 3, 0, 3, 4],
       [0, 1, 3, 3, 1, 4, 0, 2, 3, 0],
       [1, 4, 1, 4, 0, 2, 0, 4, 0, 1],
       [2, 0, 0, 2, 3, 4, 4, 2, 4, 3],
       [3, 2, 1, 3, 1, 1, 0, 2, 2, 4]])

In [23]:
lists[0] # First list

array([0, 3, 2, 3, 3, 3, 3, 0, 3, 4])

In [24]:
def transform(aListOrArrayOfLists):
    finalResults = []
    for i in aListOrArrayOfLists:
        partialResults = []
        for x in i:
            partialResults.append(x.astype(str))
        finalResults.append(partialResults)
    return finalResults

transform(lists)

[['0', '3', '2', '3', '3', '3', '3', '0', '3', '4'],
 ['0', '1', '3', '3', '1', '4', '0', '2', '3', '0'],
 ['1', '4', '1', '4', '0', '2', '0', '4', '0', '1'],
 ['2', '0', '0', '2', '3', '4', '4', '2', '4', '3'],
 ['3', '2', '1', '3', '1', '1', '0', '2', '2', '4']]

In [25]:
### Let's use functions to expand our data
### Data source: http://www.isdscotland.org/Health-Topics/Cancer/Publications/data-tables2017.asp?id=1902#1902 
! cd data && ls

cancer_all_types.xls                    risk_factors_cervical_cancer.csv
cervical-cancer-risk-classification.zip tobacco.csv
dataStore.xlsx                          world.sql
file.txt


In [26]:
data = pd.read_excel('data/cancer_all_types.xls', sheetname=6)
data.columns

Index(['id', 'hbnew', 'hb_label', 'sitenew', 'site_label', 'sexnew',
       'sex_label', 'label', 'age_label', 'trans1.1991', 'trans1.1992',
       'trans1.1993', 'trans1.1994', 'trans1.1995', 'trans1.1996',
       'trans1.1997', 'trans1.1998', 'trans1.1999', 'trans1.2000',
       'trans1.2001', 'trans1.2002', 'trans1.2003', 'trans1.2004',
       'trans1.2005', 'trans1.2006', 'trans1.2007', 'trans1.2008',
       'trans1.2009', 'trans1.2010', 'trans1.2011', 'trans1.2012',
       'trans1.2013', 'trans1.2014', 'trans1.2015'],
      dtype='object')

In [27]:
data['sex_label'].unique()

array(['All Persons', 'Males', 'Females'], dtype=object)

In [28]:
women = data.loc[data['sex_label'] == 'Females']
wy2015 = women.loc[:,['age_label','trans1.2015']]

In [29]:
wy2015.describe()

trans1.2015
count    384.000000
mean     590.553925
std     1075.068354
min        2.000000
25%      104.529850
50%      365.500000
75%      604.129035
max    16266.000000

In [30]:
from random import * # Library to create a random number

# Create a new column using min and max using 'trans1.2015' column
wy2015['fixed'] = 100 
wy2015.head()

age_label  trans1.2015  fixed
98   Number of registrations: Under 5         36.0    100
99       Number of registrations: 5..         14.0    100
100    Number of registrations: 10-14         10.0    100
101    Number of registrations: 15-19         35.0    100
102    Number of registrations: 20-24         64.0    100

In [31]:
wy2015['func_inside'] = wy2015['trans1.2015'].apply(lambda row: row + randint(wy2015['trans1.2015'].min(),100))
wy2015.head()

age_label  trans1.2015  fixed  func_inside
98   Number of registrations: Under 5         36.0    100         65.0
99       Number of registrations: 5..         14.0    100         58.0
100    Number of registrations: 10-14         10.0    100         94.0
101    Number of registrations: 15-19         35.0    100         96.0
102    Number of registrations: 20-24         64.0    100         86.0

In [32]:
functionOutside = lambda row: row + randint(wy2015['trans1.2015'].min(),wy2015['trans1.2015'].max())

wy2015['funcOutVar'] = wy2015['trans1.2015'].apply(functionOutside)
wy2015.head()

age_label  trans1.2015  fixed  func_inside  \
98   Number of registrations: Under 5         36.0    100         65.0   
99       Number of registrations: 5..         14.0    100         58.0   
100    Number of registrations: 10-14         10.0    100         94.0   
101    Number of registrations: 15-19         35.0    100         96.0   
102    Number of registrations: 20-24         64.0    100         86.0   

     funcOutVar  
98       4880.0  
99       6011.0  
100     12684.0  
101     10310.0  
102      8513.0

In [33]:
def expandingData(row):
    return np.sqrt(row['trans1.2015'])

wy2015['funcOut'] = wy2015.apply (lambda row: expandingData(row), axis=1)
wy2015.head()

age_label  trans1.2015  fixed  func_inside  \
98   Number of registrations: Under 5         36.0    100         65.0   
99       Number of registrations: 5..         14.0    100         58.0   
100    Number of registrations: 10-14         10.0    100         94.0   
101    Number of registrations: 15-19         35.0    100         96.0   
102    Number of registrations: 20-24         64.0    100         86.0   

     funcOutVar   funcOut  
98       4880.0  6.000000  
99       6011.0  3.741657  
100     12684.0  3.162278  
101     10310.0  5.916080  
102      8513.0  8.000000

In [34]:
strings = lambda row: row.split(":")[-1].strip()

wy2015['age_label'] = wy2015['age_label'].map(strings)
wy2015.head()

age_label  trans1.2015  fixed  func_inside  funcOutVar   funcOut
98    Under 5         36.0    100         65.0      4880.0  6.000000
99        5..         14.0    100         58.0      6011.0  3.741657
100     10-14         10.0    100         94.0     12684.0  3.162278
101     15-19         35.0    100         96.0     10310.0  5.916080
102     20-24         64.0    100         86.0      8513.0  8.000000

In [35]:
result = wy2015.loc[wy2015['age_label'] == '15-19']
result

age_label  trans1.2015  fixed  func_inside    funcOutVar   funcOut
101     15-19    35.000000    100    96.000000  10310.000000  5.916080
121     15-19    23.614185    100   122.614185   4480.614185  4.859443
252     15-19     5.000000    100    46.000000  14334.000000  2.236068
272     15-19    13.241175    100   101.241175   6163.241175  3.638843
405     15-19     9.000000    100    78.000000   9553.000000  3.000000
425     15-19    22.088058    100   121.088058  10898.088058  4.699793
558     15-19    21.000000    100   107.000000  14900.000000  4.582576
578     15-19    30.125235    100   108.125235   5889.125235  5.488646

## Test 

In [36]:
# Parse HTML data from Wikipedia with numerical data
# Loc cases choosing values more than the mean of a Series
# Expand that dataset creating a new column based on a previous column. Use Lambda function (Map type)
# Export your results to a CSV

Project plannning!!!